services:
  - type: web
    name: ezchords
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: FLASK_ENV
        value: production
    secretFiles:
      - name: YouTube cookies
        filePath: cookies.txt
